export const levels = [
  {
    id: 1,
    title: 'అక్షరాలు',
    subtitle: 'Achchulu and simple padhalu',
    description:
      'Start with basic Telugu vowels and a few easy words children hear often.',
    passingScore: 5,
    lessons: [
      {
        letter: 'అ',
        transliteration: 'a',
        word: 'అమ్మ',
        meaning: 'mother',
        emoji: '👩',
      },
      {
        letter: 'ఆ',
        transliteration: 'aa',
        word: 'ఆట',
        meaning: 'game',
        emoji: '⚽',
      },
      {
        letter: 'ఇ',
        transliteration: 'i',
        word: 'ఇల్లు',
        meaning: 'house',
        emoji: '🏠',
      },
      {
        letter: 'ఈ',
        transliteration: 'ee',
        word: 'ఈగ',
        meaning: 'fly',
        emoji: '🪰',
      },
      {
        letter: 'ఉ',
        transliteration: 'u',
        word: 'ఉడుత',
        meaning: 'squirrel',
        emoji: '🐿️',
      },
      {
        letter: 'ఊ',
        transliteration: 'oo',
        word: 'ఊయల',
        meaning: 'swing',
        emoji: '🛝',
      },
      {
        letter: 'ఎ',
        transliteration: 'e',
        word: 'ఎద్దు',
        meaning: 'bull',
        emoji: '🐂',
      },
      {
        letter: 'ఏ',
        transliteration: 'ae',
        word: 'ఏడు',
        meaning: 'seven',
        emoji: '7️⃣',
      },
    ],
    quiz: [
      {
        id: 'l1-q1',
        prompt: 'Which letter matches the sound "aa"?',
        options: ['అ', 'ఆ', 'ఇ'],
        answer: 'ఆ',
      },
      {
        id: 'l1-q2',
        prompt: 'Which word starts with ఇ?',
        options: ['ఇల్లు', 'అమ్మ', 'ఊయల'],
        answer: 'ఇల్లు',
      },
      {
        id: 'l1-q3',
        prompt: 'Which picture matches ఈగ?',
        options: ['🪰', '🐂', '⚽'],
        answer: '🪰',
      },
      {
        id: 'l1-q4',
        prompt: 'Which letter is used at the start of ఉడుత?',
        options: ['ఉ', 'ఎ', 'ఏ'],
        answer: 'ఉ',
      },
      {
        id: 'l1-q5',
        prompt: 'Which word means swing?',
        options: ['ఊయల', 'ఆట', 'అమ్మ'],
        answer: 'ఊయల',
      },
      {
        id: 'l1-q6',
        prompt: 'Which number word begins with ఏ?',
        options: ['ఎద్దు', 'ఏడు', 'ఈగ'],
        answer: 'ఏడు',
      },
    ],
  },
  {
    id: 2,
    title: 'గుణింతాలు',
    subtitle: 'Guninthalu and common words',
    description:
      'Learn how vowel signs change consonants and read common words built from them.',
    passingScore: 5,
    lessons: [
      {
        letter: 'క',
        transliteration: 'ka',
        word: 'కలం',
        meaning: 'pen',
        emoji: '🖊️',
      },
      {
        letter: 'కా',
        transliteration: 'kaa',
        word: 'కాకి',
        meaning: 'crow',
        emoji: '🐦',
      },
      {
        letter: 'కి',
        transliteration: 'ki',
        word: 'కిరణం',
        meaning: 'ray',
        emoji: '☀️',
      },
      {
        letter: 'కీ',
        transliteration: 'kee',
        word: 'కీలు',
        meaning: 'key',
        emoji: '🔑',
      },
      {
        letter: 'కు',
        transliteration: 'ku',
        word: 'కుటుంబం',
        meaning: 'family',
        emoji: '👨‍👩‍👧‍👦',
      },
      {
        letter: 'కూ',
        transliteration: 'koo',
        word: 'కూర',
        meaning: 'curry',
        emoji: '🥘',
      },
      {
        letter: 'కె',
        transliteration: 'ke',
        word: 'కెరటం',
        meaning: 'wave',
        emoji: '🌊',
      },
      {
        letter: 'కో',
        transliteration: 'ko',
        word: 'కోతి',
        meaning: 'monkey',
        emoji: '🐒',
      },
    ],
    quiz: [
      {
        id: 'l2-q1',
        prompt: 'Which form shows the long aa sound?',
        options: ['కా', 'కి', 'కు'],
        answer: 'కా',
      },
      {
        id: 'l2-q2',
        prompt: 'Which word uses the ee sound?',
        options: ['కీలు', 'కలం', 'కూర'],
        answer: 'కీలు',
      },
      {
        id: 'l2-q3',
        prompt: 'Which picture matches కోతి?',
        options: ['🐒', '🔑', '🌊'],
        answer: '🐒',
      },
      {
        id: 'l2-q4',
        prompt: 'Which option starts with కు?',
        options: ['కుటుంబం', 'కిరణం', 'కాకి'],
        answer: 'కుటుంబం',
      },
      {
        id: 'l2-q5',
        prompt: 'Which sound matches కె?',
        options: ['ke', 'koo', 'kaa'],
        answer: 'ke',
      },
      {
        id: 'l2-q6',
        prompt: 'Which word means crow?',
        options: ['కోతి', 'కాకి', 'కలం'],
        answer: 'కాకి',
      },
    ],
  },
  {
    id: 3,
    title: 'వత్తులు',
    subtitle: 'Vattulu and joined-letter words',
    description:
      'Practice common joined consonant forms seen in everyday Telugu words.',
    passingScore: 5,
    lessons: [
      {
        letter: 'మ్మ',
        transliteration: 'mma',
        word: 'అమ్మ',
        meaning: 'mother',
        emoji: '👩',
      },
      {
        letter: 'న్న',
        transliteration: 'nna',
        word: 'అన్న',
        meaning: 'elder brother',
        emoji: '👦',
      },
      {
        letter: 'క్క',
        transliteration: 'kka',
        word: 'చెక్క',
        meaning: 'wood piece',
        emoji: '🪵',
      },
      {
        letter: 'ల్ల',
        transliteration: 'lla',
        word: 'బల్లి',
        meaning: 'lizard',
        emoji: '🦎',
      },
      {
        letter: 'ట్ట',
        transliteration: 'tta',
        word: 'బుట్ట',
        meaning: 'basket',
        emoji: '🧺',
      },
      {
        letter: 'ప్ప',
        transliteration: 'ppa',
        word: 'చప్పట్లు',
        meaning: 'claps',
        emoji: '👏',
      },
      {
        letter: 'ద్ద',
        transliteration: 'dda',
        word: 'ఎద్దు',
        meaning: 'bull',
        emoji: '🐂',
      },
      {
        letter: 'గ్గ',
        transliteration: 'gga',
        word: 'ముగ్గు',
        meaning: 'rangoli pattern',
        emoji: '🪷',
      },
    ],
    quiz: [
      {
        id: 'l3-q1',
        prompt: 'Which word contains మ్మ?',
        options: ['అమ్మ', 'బుట్ట', 'ఎద్దు'],
        answer: 'అమ్మ',
      },
      {
        id: 'l3-q2',
        prompt: 'Which joined form is used in బల్లి?',
        options: ['ప్ప', 'ల్ల', 'ట్ట'],
        answer: 'ల్ల',
      },
      {
        id: 'l3-q3',
        prompt: 'Which picture matches బుట్ట?',
        options: ['🧺', '🐂', '🪵'],
        answer: '🧺',
      },
      {
        id: 'l3-q4',
        prompt: 'Which word has the గ్గ form?',
        options: ['ముగ్గు', 'చప్పట్లు', 'అన్న'],
        answer: 'ముగ్గు',
      },
      {
        id: 'l3-q5',
        prompt: 'Which joined sound matches న్న?',
        options: ['nna', 'mma', 'dda'],
        answer: 'nna',
      },
      {
        id: 'l3-q6',
        prompt: 'Which word uses ద్ద?',
        options: ['ఎద్దు', 'చెక్క', 'బల్లి'],
        answer: 'ఎద్దు',
      },
    ],
  },
  {
    id: 4,
    title: 'వాక్యాలు',
    subtitle: 'Simple reading sentences',
    description:
      'Read short sentences that combine letters, guninthalu, and vattulu in context.',
    passingScore: 5,
    lessons: [
      {
        letter: 'అమ్మ ఆడుతోంది.',
        transliteration: 'Amma aadutondi.',
        word: 'Sentence 1',
        meaning: 'Mother is playing.',
        emoji: '🎈',
      },
      {
        letter: 'అన్న ఇంటికి వెళ్లాడు.',
        transliteration: 'Anna intiki velladu.',
        word: 'Sentence 2',
        meaning: 'Brother went home.',
        emoji: '🏠',
      },
      {
        letter: 'కాకి చెట్టు మీద ఉంది.',
        transliteration: 'Kaaki chettu meeda undi.',
        word: 'Sentence 3',
        meaning: 'The crow is on the tree.',
        emoji: '🐦',
      },
      {
        letter: 'బల్లి గోడ మీద ఉంది.',
        transliteration: 'Balli goda meeda undi.',
        word: 'Sentence 4',
        meaning: 'The lizard is on the wall.',
        emoji: '🦎',
      },
      {
        letter: 'అమ్మ కూర వండింది.',
        transliteration: 'Amma koora vandindi.',
        word: 'Sentence 5',
        meaning: 'Mother cooked curry.',
        emoji: '🥘',
      },
      {
        letter: 'పిల్లలు చప్పట్లు కొట్టారు.',
        transliteration: 'Pillalu chappatlu kottaru.',
        word: 'Sentence 6',
        meaning: 'The children clapped.',
        emoji: '👏',
      },
    ],
    quiz: [
      {
        id: 'l4-q1',
        prompt: 'Which sentence is about a crow?',
        options: ['కాకి చెట్టు మీద ఉంది.', 'అమ్మ కూర వండింది.', 'అన్న ఇంటికి వెళ్లాడు.'],
        answer: 'కాకి చెట్టు మీద ఉంది.',
      },
      {
        id: 'l4-q2',
        prompt: 'Which sentence mentions home?',
        options: ['బల్లి గోడ మీద ఉంది.', 'అన్న ఇంటికి వెళ్లాడు.', 'అమ్మ ఆడుతోంది.'],
        answer: 'అన్న ఇంటికి వెళ్లాడు.',
      },
      {
        id: 'l4-q3',
        prompt: 'Which sentence is about cooking?',
        options: ['అమ్మ కూర వండింది.', 'పిల్లలు చప్పట్లు కొట్టారు.', 'కాకి చెట్టు మీద ఉంది.'],
        answer: 'అమ్మ కూర వండింది.',
      },
      {
        id: 'l4-q4',
        prompt: 'Which sentence contains the word గోడ?',
        options: ['బల్లి గోడ మీద ఉంది.', 'అమ్మ ఆడుతోంది.', 'అన్న ఇంటికి వెళ్లాడు.'],
        answer: 'బల్లి గోడ మీద ఉంది.',
      },
      {
        id: 'l4-q5',
        prompt: 'Which sentence is about clapping?',
        options: ['పిల్లలు చప్పట్లు కొట్టారు.', 'అమ్మ కూర వండింది.', 'బల్లి గోడ మీద ఉంది.'],
        answer: 'పిల్లలు చప్పట్లు కొట్టారు.',
      },
      {
        id: 'l4-q6',
        prompt: 'Which sentence uses the word చెట్టు?',
        options: ['కాకి చెట్టు మీద ఉంది.', 'అమ్మ ఆడుతోంది.', 'అన్న ఇంటికి వెళ్లాడు.'],
        answer: 'కాకి చెట్టు మీద ఉంది.',
      },
    ],
  },
];
